{"name": "test_login_01", "status": "broken", "statusDetails": {"message": "NameError: name 'data' is not defined", "trace": "self = <test_login.TestLogin object at 0x10d091ef0>\n\n    @pytest.fixture()\n    def getdata(self):\n        print('before')\n        conf = Config()\n        self.data = Datas()\n        self.request = Send_Request.Request()\n        self.host = conf.host_debug\n>       self.urls = data.url\nE       NameError: name 'data' is not defined\n\nTestCase/test_login.py:28: NameError"}, "description": "\n            用例描述：login\n        ", "attachments": [{"name": "log", "source": "0bfbb1c9-145b-438b-b8c7-4beddeca1af6-attachment.txt", "type": "text/plain"}], "start": 1586937531938, "stop": 1586937531938, "uuid": "51b5483a-c229-4e64-bb00-ea0a14fae594", "historyId": "ad46b58c6f38a9e8de6b92b522c7cbff", "testCaseId": "49d28fbbfb79bd9a490d1da4fd8fe957", "fullName": "TestCase.test_login.TestLogin#test_login_01", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Lettos-iMac.local"}, {"name": "thread", "value": "64818-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}