{"uuid": "3e07007f-e768-4241-b783-12285c7e08b1", "children": ["1b9779cb-79f4-4b81-b347-b9368d163cd0"], "befores": [{"name": "getdata", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/test/work/API_Testframe/Params/Param/tcData.xlsx'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/test/work/API_Testframe/TestCase/test_login.py\", line 25, in getdata\n    ex_data=ParseExcel()\n  File \"/Users/test/work/API_Testframe/Params/parseExcel.py\", line 11, in __init__\n    self.wk = load_workbook(data_dir)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpyxl/reader/excel.py\", line 311, in load_workbook\n    data_only, keep_links)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpyxl/reader/excel.py\", line 126, in __init__\n    self.archive = _validate_archive(fn)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpyxl/reader/excel.py\", line 98, in _validate_archive\n    archive = ZipFile(filename, 'r')\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py\", line 1090, in __init__\n    self.fp = io.open(file, filemode)\n"}, "start": 1588744457313, "stop": 1588744457313}], "start": 1588744457313, "stop": 1588744457548}