{"uuid": "0bdc87a5-41c8-4e17-8deb-4a236e0b76e3", "children": ["8e9f27f6-69cc-43fa-a95f-a365db2909a9"], "befores": [{"name": "action", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'environment'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/test/work/API_Automation/TestCase/conftest.py\", line 35, in action\n    allure.environment(environment=env)\n"}, "start": 1586763592804, "stop": 1586763592804}], "start": 1586763592804, "stop": 1586763592899}