{"uuid": "bd662d6a-003f-48a4-9bc5-54e06e26f430", "children": ["e7bbfca5-889b-4190-9eba-037dabcdaf49"], "befores": [{"name": "action", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'environment'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/test/work/API_Automation/TestCase/conftest.py\", line 35, in action\n    allure.environment(environment=env)\n"}, "start": 1586763489578, "stop": 1586763489578}], "start": 1586763489578, "stop": 1586763489583}